Auto midi port
midi-app-controller/midi-app-controller pull request #58
Opened 2024-03-30 18:29 UTC by modyf01

automatic selection of MIDI ports based on fields in the controller's yaml

2024-03-31 18:08 UTC, lukaszsmolinski requested changes

2024-04-25 14:53 UTC, lukaszsmolinski approved these changes

2024-04-27 04:40 UTC, modyf01 commented on midi_app_controller/gui/_tests/test_binds_editor.py
> +def test_binds_editor_save_and_exit_no_mock(binds_editor_fixture_basic):
d

2024-04-27 15:04 UTC, modyf01 commented on midi_app_controller/gui/_tests/test_midi_status.py
> +    midi_status_fixture.current_controller.textActivated.emit(controller_names[0])
f

2024-05-03 16:37 UTC, Aleshkev approved these changes

2024-05-03 16:37 UTC, Aleshkev commented on midi_app_controller/gui/utils.py
> +        subpath_str = ""
I don't think this is a good idea. This way `is_subpath(None, "a/b")` is True and `is_subpath(None, None)` is True, and `is_subpath("a", None)` is False, and it isn't clear to me what any of this means. I think checking for None outside the function makes more sense. Else, there should be more description of what this function does with Nones, and also type hints should be changed to `Optional[None]`.

2024-05-03 16:37 UTC, Aleshkev commented on midi_app_controller/gui/utils.py
> +        self.addItems(self.get_items())
what is this for? There is already `refresh_items` which makes sure not to deselect the item already selected by user, I think it does everything you'd want, so maybe rename `refresh_items` to `refresh` if it's a clearer name?

2024-05-03 16:37 UTC, Aleshkev commented on midi_app_controller/state/state_manager.py
> +        print(f"Selecting binds: {binds_file}")
i think we have so far avoided printing anything to console

2024-05-03 16:38 UTC, Aleshkev commented on midi_app_controller/gui/utils.py
> +        self.addItems(self.get_items())
Oops now that I look at it, it's probably a mistake from merging. Anyway, please remove

2024-05-04 10:49 UTC, lukaszsmolinski commented
Strange things happening in recent commits 🤔 Maybe merge #51 first so we can see the real changes made in this PR.

2024-05-05 09:46 UTC, lukaszsmolinski requested changes
There are still many `print` statements, etc.

This PR should only add automatic selection of MIDI ports. I won't approve it until the changes from #51 are either removed or #51 is merged into `main` and then `main` is merged into this branch.

2024-05-15 19:58 UTC, lukaszsmolinski commented
Any progress with resolving the conflicts and deleting unrelated changes?

2024-06-13 11:28 UTC, lukaszsmolinski commented on midi_app_controller/config_files/controllers/x_touch_mini.yaml
> +preferred_midi_out: "Midi Through:Midi Through Port-0 14:0"
Incorrect port names.

2024-06-13 11:37 UTC, lukaszsmolinski requested changes

2024-06-13 11:37 UTC, lukaszsmolinski commented on midi_app_controller/config_files/controllers/x_touch_mini.yaml
> +preferred_midi_out: "Midi Through:Midi Through Port-0 14:0"
Incorrect port names. I would also change them in `docs/controllers.md` because someone may think that these ports will work with all controllers.

2024-06-13 11:37 UTC, lukaszsmolinski commented on midi_app_controller/state/state_manager.py
> +        port_name is either in or out
`.` is missing.

2024-06-13 11:37 UTC, lukaszsmolinski commented on midi_app_controller/state/state_manager.py
> +        """Selects default port for the controller"""
`.` is missing.

2024-06-13 11:37 UTC, lukaszsmolinski commented on midi_app_controller/state/state_manager.py
> +    def select_default_controller(self):
Maybe `select_default_midi_ports` instead?

2024-06-13 11:37 UTC, lukaszsmolinski commented on midi_app_controller/state/state_manager.py
> +                and controller.preferred_midi_in in self.get_available_midi_in()
It can be simplified. If `controller.preferred_midi_in` is `None` then it will not be in `self.get_available_midi_in()`.

2024-06-19 21:24 UTC, lukaszsmolinski requested changes

2024-06-19 21:24 UTC, lukaszsmolinski commented on midi_app_controller/config_files/controllers/x_touch_mini.yaml
> +preferred_midi_out: None
These fields are equal to the **string** `None` now. If we want them to be `None` in Python, they should be deleted from here and `= None`  should be added in the declaration of these attributes.

2024-06-19 22:02 UTC, lukaszsmolinski approved these changes

2024-06-19 22:29 UTC, merged