Add docs
midi-app-controller/midi-app-controller pull request #69
Opened 2024-04-28 14:21 UTC by Aleshkev

Don't review yet, I'm just trying to get readthedocs to build this >///<

2024-04-28 14:28 UTC, Aleshkev commented
It works, you can see the built docs here: https://midi-app-controller.readthedocs.io/en/add-docs/

2024-05-04 10:37 UTC, lukaszsmolinski commented on docs/index.md
> +MIDI App Controller is a package designed to integrate MIDI controllers with Python Qt apps using app-model. As of now, it is used most commonly with [napari](napari.org), a viewer for multi-dimensio
The link to napari is broken. It directs to `https://midi-app-controller.readthedocs.io/en/add-docs/napari.org`.

2024-05-04 10:37 UTC, lukaszsmolinski commented on docs/index.md
> +```
I would delete it or comment it out to avoid confusion. I think that the TODO is sufficient.

2024-05-04 10:37 UTC, lukaszsmolinski commented on docs/index.md
> +napari
I would remove the `napari` command as this section is mainly about `Installation`.

2024-05-04 10:37 UTC, lukaszsmolinski commented on docs/index.md
> +If your MIDI controller is supported out of the box, you can simply select the appropriate model. If not, you will need to tell MIDI App Controller how to interact with this model of controller by cr
`by creating a [controller schema]`
But how to do it? There is some info about it in the `Edit binds` section. But I think that a new `.md` file dedicated to config files (read-only files vs user files, default paths, etc.) would be helpful.

2024-05-04 10:37 UTC, lukaszsmolinski commented on docs/binds.md
> +Built-in schemas are available in [config_files/binds](https://github.com/midi-app-controller/midi-app-controller/tree/main/config_files/binds) at GitHub.
```suggestion
Built-in schemas are available in [config_files/binds](https://github.com/midi-app-controller/midi-app-controller/tree/main/config_files/binds) on GitHub.
```

2024-05-04 10:37 UTC, lukaszsmolinski commented on docs/controllers.md
> +Built-in schemas are available in [config_files/controllers](https://github.com/midi-app-controller/midi-app-controller/tree/main/config_files/controllers) at GitHub.
```suggestion
Built-in schemas are available in [config_files/controllers](https://github.com/midi-app-controller/midi-app-controller/tree/main/config_files/controllers) on GitHub.
```

2024-05-04 10:40 UTC, lukaszsmolinski commented on docs/controllers.md
> +Built-in schemas are available in [config_files/controllers](https://github.com/midi-app-controller/midi-app-controller/tree/main/config_files/controllers) at GitHub.
It looks like [`on` is more commonly used](https://ell.stackexchange.com/questions/89101/in-on-or-at-github).

2024-05-04 17:37 UTC, lukaszsmolinski approved these changes

2024-05-12 10:37 UTC, lukaszsmolinski requested changes
The two issues mentioned above need to be resolved.

2024-05-13 14:55 UTC, lukaszsmolinski approved these changes

2024-05-14 14:37 UTC, merged