Add default midi channel
midi-app-controller/midi-app-controller pull request #76
Opened 2024-05-07 18:34 UTC by Jokilos

2024-05-07 19:20 UTC, lukaszsmolinski approved these changes

2024-05-07 19:20 UTC, lukaszsmolinski commented on docs/controllers.md
> +  the MIDI message is decreased by 1, so it fits in a single hex digit. Should be in the range `[1, 16]`.
```suggestion
  the MIDI message is decreased by `1`, so it fits in a single hex digit. Should be in the range `[1, 16]`.
```

2024-05-07 19:20 UTC, lukaszsmolinski commented on midi_app_controller/models/controller.py
> +    default_channel: int = Field(ge=1, le=16)
Add it to the docstring.

2024-05-15 19:55 UTC, lukaszsmolinski requested changes
The issue mentioned above need to be resolved.

2024-05-17 13:49 UTC, lukaszsmolinski approved these changes

2024-05-26 11:58 UTC, modyf01 approved these changes

2024-05-30 13:41 UTC, merged